# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/ai770741/Documents/TP_Brost/tp2_p2/video_vga_7511_zed/zed_board.xdc

# Block Designs: bd/design_2/design_2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2 || ORIG_REF_NAME==design_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_clk_wiz_0_0/design_2_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_clk_wiz_0_0 || ORIG_REF_NAME==design_2_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlconstant_0_0/design_2_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xlconstant_0_0 || ORIG_REF_NAME==design_2_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlslice_1_0/design_2_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xlslice_1_0 || ORIG_REF_NAME==design_2_xlslice_1_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlconstant_1_0/design_2_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xlconstant_1_0 || ORIG_REF_NAME==design_2_xlconstant_1_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_v_tc_0_0/design_2_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_v_tc_0_0 || ORIG_REF_NAME==design_2_v_tc_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_v_axi4s_vid_out_0_0/design_2_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==design_2_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlconstant_2_0/design_2_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xlconstant_2_0 || ORIG_REF_NAME==design_2_xlconstant_2_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlconcat_0_0/design_2_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xlconcat_0_0 || ORIG_REF_NAME==design_2_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlconstant_5_0/design_2_xlconstant_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xlconstant_5_0 || ORIG_REF_NAME==design_2_xlconstant_5_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_i2c_sender_adv7511_0_0/design_2_i2c_sender_adv7511_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_i2c_sender_adv7511_0_0 || ORIG_REF_NAME==design_2_i2c_sender_adv7511_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_bram_ctrl_0_0/design_2_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_axi_bram_ctrl_0_0 || ORIG_REF_NAME==design_2_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_bram_ctrl_0_bram_0/design_2_axi_bram_ctrl_0_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==design_2_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_jtag_axi_0_0/design_2_jtag_axi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_jtag_axi_0_0 || ORIG_REF_NAME==design_2_jtag_axi_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_smartconnect_0_0/design_2_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_smartconnect_0_0 || ORIG_REF_NAME==design_2_smartconnect_0_0} -quiet] -quiet

# Block Designs: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/bd_0c5c.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_0/bd_0c5c_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_1/bd_0c5c_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_2/bd_0c5c_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_3/bd_0c5c_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_4/bd_0c5c_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_5/bd_0c5c_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_6/bd_0c5c_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_7/bd_0c5c_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_8/bd_0c5c_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_9/bd_0c5c_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_10/bd_0c5c_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_11/bd_0c5c_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_12/bd_0c5c_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_13/bd_0c5c_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_14/bd_0c5c_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_15/bd_0c5c_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_16/bd_0c5c_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_17/bd_0c5c_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_18/bd_0c5c_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_19/bd_0c5c_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_20/bd_0c5c_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_21/bd_0c5c_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_22/bd_0c5c_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_23/bd_0c5c_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_24/bd_0c5c_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_25/bd_0c5c_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_26/bd_0c5c_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_27/bd_0c5c_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_28/bd_0c5c_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_29/bd_0c5c_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_30/bd_0c5c_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_31/bd_0c5c_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_im_load_mm_0_0/design_2_im_load_mm_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_im_load_mm_0_0 || ORIG_REF_NAME==design_2_im_load_mm_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlconstant_1_1/design_2_xlconstant_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xlconstant_1_1 || ORIG_REF_NAME==design_2_xlconstant_1_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_proc_sys_reset_0_0/design_2_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_proc_sys_reset_0_0 || ORIG_REF_NAME==design_2_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_proc_sys_reset_0_1/design_2_proc_sys_reset_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_proc_sys_reset_0_1 || ORIG_REF_NAME==design_2_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_incrust_0_0/design_2_incrust_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_incrust_0_0 || ORIG_REF_NAME==design_2_incrust_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_jtag_axi_1_0/design_2_jtag_axi_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_jtag_axi_1_0 || ORIG_REF_NAME==design_2_jtag_axi_1_0} -quiet] -quiet

# XDC: bd/design_2/ip/design_2_clk_wiz_0_0/design_2_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_clk_wiz_0_0 || ORIG_REF_NAME==design_2_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_clk_wiz_0_0/design_2_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_clk_wiz_0_0 || ORIG_REF_NAME==design_2_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_clk_wiz_0_0/design_2_clk_wiz_0_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_v_tc_0_0/design_2_v_tc_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_v_tc_0_0 || ORIG_REF_NAME==design_2_v_tc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_v_tc_0_0/design_2_v_tc_0_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_v_axi4s_vid_out_0_0/design_2_v_axi4s_vid_out_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==design_2_v_axi4s_vid_out_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_v_axi4s_vid_out_0_0/design_2_v_axi4s_vid_out_0_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_axi_bram_ctrl_0_0/design_2_axi_bram_ctrl_0_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_axi_bram_ctrl_0_bram_0/design_2_axi_bram_ctrl_0_bram_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_jtag_axi_0_0/constraints/jtag_axi.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_jtag_axi_0_0 || ORIG_REF_NAME==design_2_jtag_axi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_jtag_axi_0_0/design_2_jtag_axi_0_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_1/bd_0c5c_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_1/bd_0c5c_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_2/bd_0c5c_arsw_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_3/bd_0c5c_rsw_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_4/bd_0c5c_awsw_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_5/bd_0c5c_wsw_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_6/bd_0c5c_bsw_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_10/bd_0c5c_s00a2s_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_11/bd_0c5c_sarn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_12/bd_0c5c_srn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_13/bd_0c5c_sawn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_14/bd_0c5c_swn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_15/bd_0c5c_sbn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_19/bd_0c5c_s01a2s_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_20/bd_0c5c_sarn_1_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_21/bd_0c5c_srn_1_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_22/bd_0c5c_sawn_1_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_23/bd_0c5c_swn_1_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_24/bd_0c5c_sbn_1_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_25/bd_0c5c_m00s2a_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_26/bd_0c5c_m00arn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_27/bd_0c5c_m00rn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_28/bd_0c5c_m00awn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_29/bd_0c5c_m00wn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_30/bd_0c5c_m00bn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/ooc.xdc

# XDC: bd/design_2/ip/design_2_im_load_mm_0_0/constraints/im_load_mm_ooc.xdc

# XDC: bd/design_2/ip/design_2_proc_sys_reset_0_0/design_2_proc_sys_reset_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_proc_sys_reset_0_0 || ORIG_REF_NAME==design_2_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_proc_sys_reset_0_0/design_2_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_proc_sys_reset_0_0 || ORIG_REF_NAME==design_2_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_proc_sys_reset_0_0/design_2_proc_sys_reset_0_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_proc_sys_reset_0_1/design_2_proc_sys_reset_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_proc_sys_reset_0_1 || ORIG_REF_NAME==design_2_proc_sys_reset_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_proc_sys_reset_0_1/design_2_proc_sys_reset_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_proc_sys_reset_0_1 || ORIG_REF_NAME==design_2_proc_sys_reset_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_proc_sys_reset_0_1/design_2_proc_sys_reset_0_1_ooc.xdc

# XDC: bd/design_2/ip/design_2_incrust_0_0/constraints/incrust_ooc.xdc

# XDC: bd/design_2/ip/design_2_jtag_axi_1_0/constraints/jtag_axi.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_jtag_axi_1_0 || ORIG_REF_NAME==design_2_jtag_axi_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_jtag_axi_1_0/design_2_jtag_axi_1_0_ooc.xdc

# XDC: bd/design_2/design_2_ooc.xdc
